version: '3.4'

services:
  epicmqttbridge:
    image: epicmqttbridge
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./config.yml:/app/config.yml